services:
  api_mhealth:
    build: .
    container_name: api_mhealth
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: mysql://viier:viier@mhealth_mysql:3306/mhealth
      DATABASE_HOST: mhealth_mysql
      DATABASE_PORT: 3306
      DATABASE_USER: viier
      DATABASE_PASSWORD: viier
      DATABASE_NAME: mhealth
      DEVMODE: "true"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
